import { StudyMaterial } from '../types';

export const SAMPLE_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: 'sample-os-memory',
    name: 'Operating Systems: Virtual Memory & Paging.txt',
    type: 'text',
    size: 4280,
    active: true,
    wordCount: 780,
    uploadedAt: Date.now() - 3600000 * 2,
    summary: 'Detailed lecture notes on Virtual Memory, Page Tables, TLB cache hits/misses, and Page Replacement Algorithms (FIFO, LRU, Clock algorithm).',
    topics: ['Virtual Memory', 'Paging', 'TLB', 'Page Faults', 'LRU'],
    content: `# Chapter 9: Virtual Memory & Page Replacement

## 1. Virtual Memory Fundamentals
Virtual memory is a memory management capability of an operating system that uses hardware and software to allow a computer to compensate for physical memory shortages by temporarily transferring data from random access memory (RAM) to disk storage.
- Virtual Address Space: The logical view of how a process is stored in memory (typically 0 to 2^N-1).
- Physical Address Space: The actual physical memory (RAM) addresses on the hardware.
- Memory Management Unit (MMU): Hardware device that at run time maps virtual to physical addresses.

## 2. Paging and Translation Lookaside Buffer (TLB)
- Paging divides physical memory into fixed-sized blocks called **Frames** (typically 4KB) and logical memory into blocks of the same size called **Pages**.
- Every address generated by the CPU is divided into two parts:
  1. Page Number (p) - used as an index into a per-process Page Table.
  2. Page Offset (d) - combined with base address to define the physical memory address.
- **Translation Lookaside Buffer (TLB)**: A high-speed associative hardware cache.
  - TLB Hit: Page number found in TLB; frame retrieved in 1 clock cycle.
  - TLB Miss: Page table in RAM must be accessed (causes extra memory access cycles), then TLB is updated.
  - Effective Access Time (EAT) = (Hit Ratio * (TLB Search + Memory Access)) + ((1 - Hit Ratio) * (TLB Search + 2 * Memory Access)).

## 3. Page Fault Handling
When a process references a page marked "invalid" in the page table (not currently in RAM):
1. Trap to OS kernel (Page Fault interrupt).
2. Save user registers and process state.
3. Check internal tables to verify if reference was legal. If invalid address, terminate process with Segmentation Fault.
4. If legal, find a free frame in physical memory.
5. Issue I/O read to back-store (disk/SSD) to bring desired page into the allocated frame.
6. When I/O completes, update page table (mark valid bit = 1).
7. Restart the instruction that caused the page fault.

## 4. Page Replacement Algorithms
When no frame is free:
- **FIFO (First-In, First-Out)**: Replaces oldest page. Suffers from *Belady's Anomaly* (more frames can sometimes cause more page faults!).
- **Optimal (OPT / MIN)**: Replaces page that will not be used for longest period of time. Theoretically optimal, impossible to implement in practice without future knowledge.
- **Least Recently Used (LRU)**: Replaces page that has not been used for the longest period of time. Approximated via counter or stack implementation. Does not suffer from Belady's Anomaly.
- **Clock / Second-Chance Algorithm**: Uses a reference bit (0 or 1) and a circular pointer queue.`
  },
  {
    id: 'sample-crispr-genetics',
    name: 'Molecular Biology: CRISPR-Cas9 Gene Editing.md',
    type: 'markdown',
    size: 3820,
    active: true,
    wordCount: 650,
    uploadedAt: Date.now() - 3600000 * 5,
    summary: 'Overview of CRISPR-Cas9 mechanism, gRNA targeting, PAM sequence recognition, Double-Strand Breaks (DSB), and repair pathways (NHEJ vs HDR).',
    topics: ['CRISPR-Cas9', 'Guide RNA', 'PAM Sequence', 'NHEJ', 'HDR Repair'],
    content: `# Molecular Biology Lecture Notes: CRISPR-Cas9 System

## 1. Discovery and Natural Bacterial Immunity
CRISPR (Clustered Regularly Interspaced Short Palindromic Repeats) is an adaptive immune defense mechanism found in bacteria and archaea to defend against bacteriophage viruses.
- Bacteria capture snippets of invading viral DNA and integrate them into their CRISPR array as "spacers".
- Upon reinfection, the array is transcribed into CRISPR RNA (crRNA) and trans-activating crRNA (tracrRNA), guiding Cas endonucleases to cut complementary foreign viral genomes.

## 2. Components of Engineered CRISPR-Cas9
Modern engineered CRISPR-Cas9 utilizes two primary components:
1. **Cas9 Endonuclease**: The molecular scissors protein derived from *Streptococcus pyogenes* containing two catalytic domains:
   - RuvC domain (cleaves non-target DNA strand)
   - HNH domain (cleaves target DNA strand)
2. **Single Guide RNA (sgRNA / gRNA)**: A synthetic fusion of crRNA and tracrRNA. Contains a ~20 nucleotide custom targeting sequence that pairs specifically with genomic DNA.

## 3. PAM Sequence Requirement
For Cas9 to bind and unwind target DNA, the genomic sequence immediately 3' of the target must contain a **Protospacer Adjacent Motif (PAM)**.
- For *Streptococcus pyogenes* Cas9 (SpCas9), the canonical PAM is **5'-NGG-3'** (where N is any nucleotide, followed by two Guanines).
- If the PAM sequence is absent, Cas9 will not cleave the target even with 100% RNA-DNA complementary matching.

## 4. Double Strand Break (DSB) and Repair Pathways
Once Cas9 creates a blunt double-strand break (DSB) 3 base pairs upstream of the PAM, the host cell activates one of two repair mechanisms:
1. **Non-Homologous End Joining (NHEJ)**:
   - Error-prone repair pathway active throughout all cell cycle stages.
   - Frequently introduces small insertions or deletions (indels), causing frameshift mutations to knock out gene function.
2. **Homology-Directed Repair (HDR)**:
   - High-fidelity, precise repair pathway occurring primarily during S and G2 phases.
   - Requires an exogenous donor DNA repair template with homology arms to knock-in specific gene sequences or correct point mutations.`
  },
  {
    id: 'sample-macroeconomics',
    name: 'Macroeconomics: Fiscal Policy & Inflation.txt',
    type: 'text',
    size: 3410,
    active: false,
    wordCount: 590,
    uploadedAt: Date.now() - 3600000 * 24,
    summary: 'Principles of aggregate demand/supply, expansionary vs contractionary fiscal policy, Phillips Curve, and inflation dynamics.',
    topics: ['Fiscal Policy', 'Aggregate Demand', 'Inflation', 'Multiplier Effect', 'Phillips Curve'],
    content: `# Macroeconomics: Fiscal Policy, Inflation, and Output Equilibrium

## 1. Aggregate Demand & Supply Components
- Aggregate Demand (AD) = C + I + G + (X - M)
  - C = Consumer Spending
  - I = Business Investment
  - G = Government Expenditure
  - (X - M) = Net Exports (Exports minus Imports)
- Short-Run Aggregate Supply (SRAS): Slopes upward due to sticky wages and prices.
- Long-Run Aggregate Supply (LRAS): Vertical at potential GDP (Y*), determined by technology, labor force, and capital stock.

## 2. Fiscal Policy Mechanics
- **Expansionary Fiscal Policy**: Used during recessions / contractionary gaps.
  - Increase government spending (G ↑) or decrease taxes (T ↓).
  - Shifts AD curve rightward to close deflationary gap.
  - Spending Multiplier = 1 / (1 - MPC) = 1 / MPS (where MPC is Marginal Propensity to Consume).
  - Tax Multiplier = -MPC / (1 - MPC).
- **Contractionary Fiscal Policy**: Used to curb overheating and demand-pull inflation.
  - Decrease government spending (G ↓) or raise taxes (T ↑).
  - Shifts AD curve leftward.

## 3. Inflation Types and Causes
1. **Demand-Pull Inflation**: "Too much money chasing too few goods". AD increases faster than aggregate supply capacity.
2. **Cost-Push Inflation (Stagflation)**: Negative supply shock (e.g., sudden oil price spike) shifts SRAS leftward, causing output to fall while price level rises.
3. **The Phillips Curve**:
   - Short-run inverse relationship between unemployment and inflation.
   - Long-run Phillips Curve is vertical at the Natural Rate of Unemployment (NAIRU).`
  }
];
